swagger: "2.0"
info:
  title: Dolar501
  description: API que monitorea el precio del dolar en Venezuela
  version: 1.0.0
  contact:
    name: Spyridon Mihalopoulos
    email: root.spyro@gmail.com
    url: https://rootspyro.com
  license:
    name: MIT
    url: https://choosealicense.com/licenses/mit/
basePath: /api/v1
securityDefinitions:
  OauthSecurity:
    type: oauth2
    flow: accessCode
    authorizationUrl: https://github.com/login/oauth/authorize
    tokenUrl: https://github.com/login/oauth/access_token

security:
  - OauthSecurity: []

paths:  

  /auth/login:
    get:
      description: redirige al usuario al inicio de sesion en github
      security: []
      operationId: AuthLogin
      tags:
        - Auth
      responses:
        default:
          description: respuesta generica
          schema:
            $ref: "#/definitions/default"

  /auth/callback:
    get:
      description: retorna el token de acceso
      operationId: GetAuthToken
      security: []
      parameters:
        - name: code
          type: string
          in: query
          required: true
      tags:
        - Auth
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/AccessResponse"
        default:
          description: respuesta generica
          schema:
            $ref: "#/definitions/default"

  /dolar:
    get:
      description: Retorna la lista de monedas que monitorea la API
      operationId: GetDolarCurrencies
      tags:
        - Dolar
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/DolarCurrencies"
        default:
          description: respuesta generica
          schema: 
            $ref: "#/definitions/default"
            

  /dolar/{moneda}:
    get:
      description: Retorna la lista de plataformas del precio del dolar en dicha moneda
      operationId: GetCurrencyPlatforms
      tags:
        - Dolar
      parameters:
        - name: moneda
          type: string
          required: true
          in: path
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/DolarPlatforms"
        default:
          description: respuesta generica
          schema:
            $ref: "#/definitions/default"
        
        
  /dolar/{moneda}/{plataforma}:
    get:
      description: Retorna el precio del dolar en la plataforma indicada
      operationId: GetDolarPrice
      parameters:
        - name: plataforma
          type: string
          required: true
          in: path
          
        - name: moneda
          type: string
          required: true
          in: path
      tags:
        - Dolar
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/DolarPriceResponse"
        default:
          description: respuesta generica
          schema: 
            $ref: "#/definitions/default"
      
tags: 
  - name: Dolar
    description: Todos los endpoints relacionados al dolar
  - name: Auth
    description: Todos los endpoints relacionados a la autenticacion del usuario
definitions: 

  default:
    type: object
    properties:
      status:
        type: string
      data:
        type: string

  AccessResponse:
    type: object
    properties:
      status:
        type: string
      data:
        type: object
        properties:
          access_token:
            type: string
  
  DolarCurrencies:
    type: object
    properties:
      status:
        type: string
      data:
        type: array
        items:
          $ref: "#/definitions/DolarCurrency"
        
  DolarCurrency:
    type: object
    properties:
      moneda:
        type: string
      endpoint:
        type: string
  
  DolarPlatform:
    type: object
    properties:
      plataforma:
        type: string
      precio:
        type: number 
      endpoint:
        type: string
        
  DolarPlatforms:
    type: object
    properties:
      status:
        type: string
      data:
        type: array
        items:
          $ref: "#/definitions/DolarPlatform"

  DolarPrice:
    type: object
    properties:
      plataforma:
        type: string
      precio:
        type: number
      moneda:
        type: string
        
  DolarPriceResponse:
    type: object
    properties:
      status:
        type: string
      data:
        $ref: "#/definitions/DolarPrice"

  principal:
    type: string

